Дисциплина «Искусственный интеллект»

Рабочая тетрадь № 2

# Библиотека NumPy



1.1. Теоретический материал – Библиотека NumPy

NumPy (NumericalPython) - это библиотека Python с открытым
исходным кодом, которая используется практически во всех областях науки
и техники. Это универсальный стандарт для работы с числовыми данными в
Python.

Если у вас уже есть Python, вы можете установить NumPy с помощью
командной строки:
- pip install numpy

Чтобы начать использовать NumPy необходимо импортировать
соответствующую библиотеку:
 import numpy as np

Основным объектом NumPy является однородный многомерный
массив (в numpy называется numpy.ndarray). Это многомерный массив
элементов (обычно чисел), одного типа.

Наиболее важные атрибуты объектов ndarray:

- ndarray.ndim - число измерений (чаще их называют "оси") массива.

- ndarray.shape - размеры массива, его форма. Это кортеж натуральных
чисел, показывающий длину массива по каждой оси. Для матрицы из n строк
и m столбов, shape будет (n,m). Число элементов кортежа shape равно ndim.
- ndarray.size - количество элементов массива. Очевидно, равно
произведению всех элементов атрибута shape.

- ndarray.dtype - объект, описывающий тип элементов массива. Можно
определить dtype, используя стандартные типы данных Python. NumPy здесь
предоставляет целый букет возможностей, как встроенных, например: bool_,
character, int8, int16, int32, int64, float8, float16, float32, float64, complex64,
object_, так и возможность определить собственные типы данных, в том
числе и составные.

- ndarray.itemsize - размер каждого элемента массива в байтах.

- ndarray.data - буфер, содержащий фактические элементы массива.

Обычно не нужно использовать этот атрибут, так как обращаться к
элементам массива проще всего с помощью индексов.

## Примеры

1.2.1 Пример

Создать массив 5x2. Создать массив 5x2. Вывести все значения массива,значение элемента с индексом (3,1) и второй столбец. Индексация начинается с нуля.


Решение:

In [ ]:
x = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


Ответ:
```
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]
 ```

1.2.2 Пример  
Выполнить следующее:
1. Создать вектор (одномерный массив) размера 10, заполненный нулями.
2. Создать вектор размера 10, заполненный единицами.
3. Создать вектор размера 10, заполненный заданным числом.
4. Создать вектор со значениями от 10 до 19.

Решение:

In [ ]:
a=np.zeros(10)
b=np.ones(10)
c=np.full(10,5)
d=np.arange(10,20)
print(a,"\n",b,"\n",c,"\n",d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


Ответ
```
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [5 5 5 5 5 5 5 5 5 5]
 [10 11 12 13 14 15 16 17 18 19]
```

1.2.3 Пример

Создать массив 10x10 со случайными значениями, найти минимум,
максимум и среднее значение.

Решение:

In [ ]:
Z = np.random.random((10, 10))
Zmin, Zmax, Zmean = Z.min(), Z.max(),Z.mean()
print(Zmin, Zmax, Zmean)

0.008537170818247564 0.9781050207703609 0.4899579689435718


Ответ:
```
0.04013741269925819 0.9850059665792373 0.47267736481867173
```

1.2.4 Пример

Задать матрицу размерности 5 на 5 и поменять 2 строки в матрице
местами


Решение:

In [ ]:
A=np.arange(25).reshape(5,5)
A[[0,1]]=A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


Ответ:
```
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
 ```

1.2.5 Пример

Выяснить результат следующих выражений:

0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan

0.3 == 3 * 0.

In [ ]:
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.nan-np.nan)
print(0.3==3*0.1)

nan
False
False
nan
False


Ответ
```
nan
False
False
nan
False
```

1.2.6 Пример

Отсортировать массив.

In [ ]:
arr=np.array([2,1,5,3,7,4,6,8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


Ответ
```
[1 2 3 4 5 6 7 8]
```

## Задание

1.3.1 Задание

Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами.

In [ ]:
matrix = np.zeros((8, 8), dtype=int)
matrix[::2, ::2] = 1
matrix[1::2, 1::2] = 1
print(matrix)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


Ответ
```
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
 ```

1.3.2 Задание

Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
необходимо использовать функцию arrange

In [ ]:
matrix = np.zeros((5,5))
matrix += np.arange(5)
print(matrix)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


Ответ:
```
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
 ```

1.3.3 Задание

Создать массив 3x3x3 со случайными значениями.

In [ ]:
arr = np.random.rand(3, 3, 3)
print(arr)

[[[0.27795594 0.42184852 0.94038195]
  [0.78139188 0.09095546 0.03727583]
  [0.76923308 0.91215029 0.96244325]]

 [[0.69680143 0.15927427 0.08707575]
  [0.50148352 0.89993215 0.9081839 ]
  [0.20917215 0.74689548 0.27448297]]

 [[0.02562288 0.76664626 0.48039121]
  [0.39922854 0.06307193 0.83304884]
  [0.77052211 0.26521196 0.69038525]]]


Ответ:
```
[[[0.27795594 0.42184852 0.94038195]
  [0.78139188 0.09095546 0.03727583]
  [0.76923308 0.91215029 0.96244325]]

 [[0.69680143 0.15927427 0.08707575]
  [0.50148352 0.89993215 0.9081839 ]
  [0.20917215 0.74689548 0.27448297]]

 [[0.02562288 0.76664626 0.48039121]
  [0.39922854 0.06307193 0.83304884]
  [0.77052211 0.26521196 0.69038525]]]
 ```

1.3.4 Задание

Создать матрицу с 0 внутри, и 1 на границах.

In [ ]:
r = 10
c = 10
mat = np.zeros((r, c))
mat[0, :] = 1
mat[-1, :] = 1
mat[:, 0] = 1
mat[:, -1] = 1
print(mat)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Ответ:
```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
 ```

1.3.5 Задание

Создайте массив и отсортируйте его по убыванию.

In [ ]:
a = np.array([6, 5, 1, 8, 7, 3, 9, 10, 53, 105])
sorted = np.sort(a)[::-1]
print(sorted)

[105  53  10   9   8   7   6   5   3   1]


Ответ:
```
[105  53  10   9   8   7   6   5   3   1]
 ```

1.3.6 Задание

Создайте матрицу, выведите ее форму, размер и размерность.

In [ ]:
mat = np.array([[6, 2, 8, 0], [1, 4, 3, 7], [9, 5, 7, 2]])
print(mat)
print("Форма:", mat.shape)
print("Размер:", mat.size)
print("Размерность:", mat.ndim)

[[6 2 8 0]
 [1 4 3 7]
 [9 5 7 2]]
Форма: (3, 4)
Размер: 12
Размерность: 2


Ответ:
```
[[6 2 8 0]
 [1 4 3 7]
 [9 5 7 2]]
Форма: (3, 4)
Размер: 12
Размерность: 2
 ```

# Библиотека Pandas


2.1. Теоретический материал – Библиотека Pandas

Первым шагом в любом начинании в области машинного обучения
является введение исходных данных в систему. Исходные данные могут
вводиться вручную, содержаться в файле или храниться в интернете в какомлибо формате. Кроме того, часто требуется получить данные из нескольких источников.

Библиотека pandas – это удобный и быстрый инструмент для работы
с данными, обладающий большим функционалом. Если очень кратко, то
pandas – это библиотека, которая предоставляет очень удобные с точки
зрения использования инструменты для хранения данных и работе с ними.
Библиотека pandas присутствует в стандартной поставке Anaconda.
Если же ее там нет, то его можно установить отдельно. Для этого введите
командной строке:
- pip install pandas

Для импорта библиотеки используйте команду:
```
import pandas as pd
```
Библиотека pandas предоставляет две ключевые структуры данных:
Series и DataFrame.
- Series – это одномерная структура данных, ее можно представить, как
таблицу с одной строкой. С Series можно работать как с обычным массивом
(обращаться по номеру индекса), и как с ассоциированным массивом, когда
можно использовать ключ для доступа к элементам данных.
- DataFrame – это двумерная структура. Идейно она очень похожа на
обычную таблицу, что выражается в способе ее создания и работе с ее
элементами.


## Пример

2.2.1 Пример

Создать Series из списка Python, словаря Python, и массива Numpy(установить буквенные метки для последнего).

In [ ]:
lst=[1,2,3,4,5]
d={'a':1,'b':2,'c':3}
ndarr=np.array([1,2,3,4,5])

s1=pd.Series(lst)
s2=pd.Series(d)
s3=pd.Series(ndarr,['a','b','c','d','e'])

print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64


Ответ:
```
0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64
```

2.2.2 Пример

Дано два Series. Напечатать их первые элементы и все элементы после третьего (во втором фрейме)

In [ ]:
s1=pd.Series([1,2,3,4,5],['a','b','c','d','e'])
s2=pd.Series([5,4,3,2,1])
print(s1['a'])
print(s2[0])
print(s2[3:])

1
5
3    2
4    1
dtype: int64


Ответ:
```
1
5
3    2
4    1
dtype: int64
```

2.2.3 Пример

Создайте новый фрейм данных.

In [ ]:
dataframe=pd.DataFrame()
dataframe['Имя']=['Джеки Джексон','Стивен Стивенсон']
dataframe['Возраст']=[38,25]
dataframe['Водитель']=[True,False]
dataframe

Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False

2.2.4 Пример

Загрузите фрейм данных по ссылке:
https://raw.githubusercontent.com/lukes/ISO-3166-Countries-with-Regional-Codes/master/all/all.csv

In [ ]:
url="https://raw.githubusercontent.com/lukes/ISO-3166-Countries-with-Regional-Codes/master/all/all.csv"
dataframe=pd.read_csv(url)
dataframe.head(5)

name alpha-2 alpha-3  country-code     iso_3166-2   region  \
0     Afghanistan      AF     AFG             4  ISO 3166-2:AF     Asia   
1   Åland Islands      AX     ALA           248  ISO 3166-2:AX   Europe   
2         Albania      AL     ALB             8  ISO 3166-2:AL   Europe   
3         Algeria      DZ     DZA            12  ISO 3166-2:DZ   Africa   
4  American Samoa      AS     ASM            16  ISO 3166-2:AS  Oceania   

        sub-region intermediate-region  region-code  sub-region-code  \
0    Southern Asia                 NaN        142.0             34.0   
1  Northern Europe                 NaN        150.0            154.0   
2  Southern Europe                 NaN        150.0             39.0   
3  Northern Africa                 NaN          2.0             15.0   
4        Polynesia                 NaN          9.0             61.0   

   intermediate-region-code  
0                       NaN  
1                       NaN  
2                       NaN  
3                       NaN  
4                       NaN

2.2.5 Пример

Проанализировать характеристики фрейма данных.

In [ ]:
url='https://raw.githubusercontent.com/lukes/ISO-3166-Countries-with-Regional-Codes/master/all/all.csv'
dataframe=pd.read_csv(url)
print(dataframe.head(2))
print(dataframe.tail(3))
print(dataframe.shape)
print(dataframe.describe())

            name alpha-2 alpha-3  country-code     iso_3166-2  region  \
0    Afghanistan      AF     AFG             4  ISO 3166-2:AF    Asia   
1  Åland Islands      AX     ALA           248  ISO 3166-2:AX  Europe   

        sub-region intermediate-region  region-code  sub-region-code  \
0    Southern Asia                 NaN        142.0             34.0   
1  Northern Europe                 NaN        150.0            154.0   

   intermediate-region-code  
0                       NaN  
1                       NaN  
         name alpha-2 alpha-3  country-code     iso_3166-2  region  \
246     Yemen      YE     YEM           887  ISO 3166-2:YE    Asia   
247    Zambia      ZM     ZMB           894  ISO 3166-2:ZM  Africa   
248  Zimbabwe      ZW     ZWE           716  ISO 3166-2:ZW  Africa   

             sub-region intermediate-region  region-code  sub-region-code  \
246        Western Asia                 NaN        142.0            145.0   
247  Sub-Saharan Africa      Eastern A

Ответ:
```
            name alpha-2 alpha-3  country-code     iso_3166-2  region  \
0    Afghanistan      AF     AFG             4  ISO 3166-2:AF    Asia   
1  Åland Islands      AX     ALA           248  ISO 3166-2:AX  Europe   

        sub-region intermediate-region  region-code  sub-region-code  \
0    Southern Asia                 NaN        142.0             34.0   
1  Northern Europe                 NaN        150.0            154.0   

   intermediate-region-code  
0                       NaN  
1                       NaN  
         name alpha-2 alpha-3  country-code     iso_3166-2  region  \
246     Yemen      YE     YEM           887  ISO 3166-2:YE    Asia   
247    Zambia      ZM     ZMB           894  ISO 3166-2:ZM  Africa   
248  Zimbabwe      ZW     ZWE           716  ISO 3166-2:ZW  Africa   

             sub-region intermediate-region  region-code  sub-region-code  \
246        Western Asia                 NaN        142.0            145.0   
247  Sub-Saharan Africa      Eastern Africa          2.0            202.0   
248  Sub-Saharan Africa      Eastern Africa          2.0            202.0   

     intermediate-region-code  
246                       NaN  
247                      14.0  
248                      14.0  
(249, 11)
       country-code  region-code  sub-region-code  intermediate-region-code
count    249.000000   248.000000       248.000000                107.000000
mean     433.835341    65.951613       179.866935                 31.719626
std      252.980446    67.347832       138.334170                111.000322
min        4.000000     2.000000        15.000000                  5.000000
25%      218.000000     9.000000        53.750000                 11.000000
50%      434.000000    19.000000       154.000000                 14.000000
75%      652.000000   142.000000       202.000000                 29.000000
max      894.000000   150.000000       419.000000                830.000000
```

2.2.6 Пример

Выберите индивидуальные данные или срезы фрейма данных

In [ ]:
url='https://raw.githubusercontent.com/lukes/ISO-3166-Countries-with-Regional-Codes/master/all/all.csv'
dataframe=pd.read_csv(url)
dataframe.iloc[1:4]

name alpha-2 alpha-3  country-code     iso_3166-2  region  \
1  Åland Islands      AX     ALA           248  ISO 3166-2:AX  Europe   
2        Albania      AL     ALB             8  ISO 3166-2:AL  Europe   
3        Algeria      DZ     DZA            12  ISO 3166-2:DZ  Africa   

        sub-region intermediate-region  region-code  sub-region-code  \
1  Northern Europe                 NaN        150.0            154.0   
2  Southern Europe                 NaN        150.0             39.0   
3  Northern Africa                 NaN          2.0             15.0   

   intermediate-region-code  
1                       NaN  
2                       NaN  
3                       NaN

2.2.7 Пример

Требуется отобрать строки фрейма данных на основе некоторого условия. Необходимо сформировать новый фрейм данных из пассажиров первого класса.

В связи с неработоспособностью ссылки, сформируем новый фрейм данных из alpha-2 AX

In [ ]:
url='https://raw.githubusercontent.com/lukes/ISO-3166-Countries-with-Regional-Codes/master/all/all.csv'
dataframe=pd.read_csv(url)
dataframe[dataframe['alpha-2']=='AX'].head(2)

name alpha-2 alpha-3  country-code     iso_3166-2  region  \
1  Åland Islands      AX     ALA           248  ISO 3166-2:AX  Europe   

        sub-region intermediate-region  region-code  sub-region-code  \
1  Northern Europe                 NaN        150.0            154.0   

   intermediate-region-code  
1                       NaN

## Задание

2.3.1 Задание

Найдите евклидово расстояние между двумя Series (точками) a и b, не
используя встроенную формулу.

In [ ]:
a = pd.Series([5, 1, 7])
b = pd.Series([3, 2, 4])
print(sum((a - b)**2)**0.5)

3.7416573867739413


Ответ:
```
3.7416573867739413
```

2.3.2 Задание

Найдите в Интернете ссылку на любой csv файл и сформируйте из него
фрейм данных (например, коллекцию фреймов данных можно найти
здесь: https://github.com/akmand/datasets).

In [ ]:
url = 'https://raw.githubusercontent.com/akmand/datasets/main/cdc.csv'
dataframe = pd.read_csv(url)
print(dataframe.head())


     genhlth  exerany  hlthplan  smoke100  height  weight  wtdesire  age  \
0       good        0         1         0      70     175       175   77   
1       good        0         1         1      64     125       115   33   
2       good        1         1         1      60     105       105   49   
3       good        1         1         0      66     132       124   42   
4  very good        0         1         0      61     150       130   55   

  gender  
0      m  
1      f  
2      f  
3      f  
4      f  


Ответ:
```
     genhlth  exerany  hlthplan  smoke100  height  weight  wtdesire  age  \
0       good        0         1         0      70     175       175   77   
1       good        0         1         1      64     125       115   33   
2       good        1         1         1      60     105       105   49   
3       good        1         1         0      66     132       124   42   
4  very good        0         1         0      61     150       130   55   

  gender  
0      m  
1      f  
2      f  
3      f  
4      f  
```

2.3.3 Задание

Проделайте с получившемся из предыдущего задания фреймом данных те же действия, что и в примерах 2.2.5-2.2.7.

In [ ]:
import pandas as pd

url = 'https://raw.githubusercontent.com/akmand/datasets/main/cdc.csv'
dataframe = pd.read_csv(url)

print(dataframe.columns)
# Анализ характеристик фрейма
print(dataframe.head(2))
print("\n")
print(dataframe.tail(3))
print("\n")
print(dataframe.shape)
print("\n")
print(dataframe.describe())  # Печать сводной статистики
print("\n")

# Выбор отдельных данных или фрагментов
print(dataframe['genhlth'])  # Выбор одного столбца
print("\n")
print(dataframe.iloc[2:5, 3:6])  # Выбор фрагмента столбцов и строк iloc
print("\n")

# Фильтр фрейма данных на основе условия
filtered_df = dataframe[dataframe['genhlth']=='good' ]  # Выбор строк, где 1 столбец > 13.0
print(filtered_df.head())



Index(['genhlth', 'exerany', 'hlthplan', 'smoke100', 'height', 'weight',
       'wtdesire', 'age', 'gender'],
      dtype='object')
  genhlth  exerany  hlthplan  smoke100  height  weight  wtdesire  age gender
0    good        0         1         0      70     175       175   77      m
1    good        0         1         1      64     125       115   33      f


      genhlth  exerany  hlthplan  smoke100  height  weight  wtdesire  age  \
19997    poor        0         1         0      65     216       150   57   
19998    good        1         1         0      67     165       165   81   
19999    good        1         1         1      69     170       165   83   

      gender  
19997      f  
19998      f  
19999      m  


(20000, 9)


            exerany      hlthplan      smoke100        height       weight  \
count  20000.000000  20000.000000  20000.000000  20000.000000  20000.00000   
mean       0.745700      0.873800      0.472050     67.182900    169.68295   
std        0.4354

Ответ:
```
Index(['genhlth', 'exerany', 'hlthplan', 'smoke100', 'height', 'weight',
       'wtdesire', 'age', 'gender'],
      dtype='object')
  genhlth  exerany  hlthplan  smoke100  height  weight  wtdesire  age gender
0    good        0         1         0      70     175       175   77      m
1    good        0         1         1      64     125       115   33      f


      genhlth  exerany  hlthplan  smoke100  height  weight  wtdesire  age  \
19997    poor        0         1         0      65     216       150   57   
19998    good        1         1         0      67     165       165   81   
19999    good        1         1         1      69     170       165   83   

      gender  
19997      f  
19998      f  
19999      m  


(20000, 9)


            exerany      hlthplan      smoke100        height       weight  \
count  20000.000000  20000.000000  20000.000000  20000.000000  20000.00000   
mean       0.745700      0.873800      0.472050     67.182900    169.68295   
std        0.435478      0.332083      0.499231      4.125954     40.08097   
min        0.000000      0.000000      0.000000     48.000000     68.00000   
25%        0.000000      1.000000      0.000000     64.000000    140.00000   
50%        1.000000      1.000000      0.000000     67.000000    165.00000   
75%        1.000000      1.000000      1.000000     70.000000    190.00000   
max        1.000000      1.000000      1.000000     93.000000    500.00000   

           wtdesire           age  
count  20000.000000  20000.000000  
mean     155.093850     45.068250  
std       32.013306     17.192689  
min       68.000000     18.000000  
25%      130.000000     31.000000  
50%      150.000000     43.000000  
75%      175.000000     57.000000  
max      680.000000     99.000000  


0             good
1             good
2             good
3             good
4        very good
           ...    
19995         good
19996    excellent
19997         poor
19998         good
19999         good
Name: genhlth, Length: 20000, dtype: object


   smoke100  height  weight
2         1      60     105
3         0      66     132
4         0      61     150


  genhlth  exerany  hlthplan  smoke100  height  weight  wtdesire  age gender
0    good        0         1         0      70     175       175   77      m
1    good        0         1         1      64     125       115   33      f
2    good        1         1         1      60     105       105   49      f
3    good        1         1         0      66     132       124   42      f
8    good        0         1         1      65     150       130   27      f
```

# Работа с числовыми данными


3.1. Теоретический материал – Работа с числовыми данными

Количественные данные что-то измеряют – будь то размер класса,
ежемесячные продажи или оценки учащихся. Естественным способом
представления этих величин является численным (например, 150 студентов,
$529 392 продаж).

Нормализация данных — это общепринятая задача предобработки в
машинном обучении. Многие алгоритмы предполагают, что все признаки
находятся в единой шкале, как правило, от 0 до 1 или от -1 до 1.

Существует множество способов нормализации значений признаков,
чтобы масштабировать их к единому диапазону и использовать в различных
моделях машинного обучения. В зависимости от используемой функции, их
можно разделить на 2 большие группы: линейные и нелинейные. При
нелинейной нормализации в расчетных соотношениях используются
функции логистической сигмоиды или гиперболического тангенса. В
линейной нормализации изменение переменных осуществляется
пропорционально, по линейному закону.

На практике наиболее распространены следующие методы
нормализации признаков:
- Минимакс – линейное преобразование данных в диапазоне [0..1], где
минимальное и максимальное масштабируемые значения
соответствуют 0 и 1 соответственно;
- Z-масштабирование данных на основе среднего значения и
стандартного отклонения: производят деление разницы между
переменной и средним значением на стандартное отклонение.

При масштабировании данных мы будем использовать одну из
популярных библиотек машинного обучения Scikit-learn. Библиотека
содержит пакет sklearn.preprocessing, который предоставляет широкие
возможности для нормализации данных. Следует отметить, что в целом
алгоритмы обучения выигрывают от стандартизации набора данных.

##Пример

3.2.1 Пример

Прошкалируйте числовой признак в диапазон между двумя значениями

In [ ]:
import numpy as np
from sklearn import preprocessing
feature=np.array([[-500.5],[-100.1],[0],[100.1],[900.9]])
minmax_scale=preprocessing.MinMaxScaler(feature_range=(0,1))
scaled_feature=minmax_scale.fit_transform(feature)
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

Ответ:
```
array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])
```

3.2.2 Пример

Преобразуйте признак, чтобы он имел среднее значение 0 и стандартное отклонение 1

In [ ]:
import numpy as np
from sklearn import preprocessing
x=np.array([[-1000.1],[-200.2],[500.5],[600.6],[9000.9]])
scaler=preprocessing.StandardScaler()
standardized=scaler.fit_transform(x)
print("Среднее:", round(standardized.mean()))
print("Стандартное отклонение:",standardized.std())
standardized

Среднее: 0
Стандартное отклонение: 1.0


array([[-0.76058269],
       [-0.54177196],
       [-0.35009716],
       [-0.32271504],
       [ 1.97516685]])

Ответ:
```
Среднее: 0
Стандартное отклонение: 1.0
array([[-0.76058269],
       [-0.54177196],
       [-0.35009716],
       [-0.32271504],
       [ 1.97516685]])
```

3.2.3. Пример

Дан фрейм данных

dfTest = pd.DataFrame

({'A':[14.00,90.20,90.95,96.27,91.21],

'B':[103.02,107.26,110.35,114.23,114.68],

'C':['big','small','big','small','small']})
    
Необходимо масштабировать его числовые столбцы.

In [ ]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
dfTest=pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
'B':[103.02,107.26,110.35,114.23,114.68],
'C':['big','small','big','small','small']})

dfTest[['A','B']]=scaler.fit_transform(dfTest[['A','B']])
dfTest

A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

## Задание

3.3.2 Задание

Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака
(sepal_length_cm) с использованием минимаксного преобразования, а
второго (sepal_width_cm) с задействованием z-масштабирования.

In [ ]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler
url = "https://raw.githubusercontent.com/akmand/datasets/master/iris.csv"
df = pd.read_csv(url)
X = df.drop('species', axis=1)
y = df['species']
scaler_minmax = MinMaxScaler()
X['sepal_length_cm'] = scaler_minmax.fit_transform(X[['sepal_length_cm']])
scaler_z = StandardScaler()
X['sepal_width_cm'] = scaler_z.fit_transform(X[['sepal_width_cm']])
print(X.head(2))

   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm
0         0.222222        1.032057              1.4             0.2
1         0.166667       -0.124958              1.4             0.2


Ответ:
```
   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm
0         0.222222        1.032057              1.4             0.2
1         0.166667       -0.124958              1.4             0.2
```